#
# ███████╗ █████╗ ███████╗███████╗███╗   ██╗███████╗████████╗
# ██╔════╝██╔══██╗██╔════╝██╔════╝████╗  ██║██╔════╝╚══██╔══╝
# ███████╗███████║█████╗  █████╗  ██╔██╗ ██║█████╗     ██║
# ╚════██║██╔══██║██╔══╝  ██╔══╝  ██║╚██╗██║██╔══╝     ██║
# ███████║██║  ██║██║     ███████╗██║ ╚████║███████╗   ██║
# ╚══════╝╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═══╝╚══════╝   ╚═╝
#
# Plugin made by dejvokep (https://dejvokep.dev/).
#
# ► Need any help?
# Join the Discord server (https://discord.com/invite/BbhADEy) and we will more than happily help you :) (nonstop 24/7 bot support)
#
# Config version:
# - IMPORTANT >> Do NOT change unless you know what you are doing. Changing this might break the plugin.
config-version: 2
# Passphrase:
# - It is recommended to change this once in a while. Generate a new one using "/sn generate".
passphrase: ""
# Disconnect message sent to the player if their connection is unauthorized:
# - "\n" can be used for a new line.
disconnect-message: "&7[&6SafeNET&7] &cPlease connect with address: yourserver.com!\n\n&7&oIf you believe this is an error, contact server administrators."
# Enable metrics:
# - Anonymous data sending including but not limited to country in which is the server hosted, number of cores, amount
#   of players online. These statistics are used to determine the usage of the plugin and are freely viewable online.
# - When changed, to take effect server restart is needed.
metrics: true
# Address whitelisting:
# - IMPORTANT >> This is NOT any kind of security feature, just a "decoration".
# - Allows whitelisting of addresses which players used to connect with.
address-whitelist:
  # Enabled:
  enabled: false
  # Whitelisted addresses - these should be the proxy IPs / DNS names you want players to connect with:
  # - Each entry in the list should either be IP (IPv4) or DNS name you want players to connect with to the proxy server.
  # - Port must be specified after each entry separated by colon (IP/DNS name:port).
  # - If your server has dynamic IP, use the "{ip}" placeholder as the server's IP. Please configure the ip-website
  #   field, too.
  # - DNS servers do not recognize the case-sensitivity, so does not the plugin. If you would like to disable this for a
  #   certain address (to be compared case-sensitively), put an exclamation mark before it, like !test.yourserver.com.
  addresses: [ ]
  # Website used to obtain the value of the "{ip}" placeholder (the public IP of your server):
  # - This should be a website that returns only your IP on the HTTP GET request (if you open it in your browser).
  # - IMPORTANT >> Pick a server carefully to avoid data and privacy information leaks.
  ip-website: ""
# Command messages:
command:
  # If a player runs the command:
  console-only: "&7[&6SafeNET&7] Command is available only in the console."
  # If sender uses an invalid format of a command:
  invalid-format: "&7[&6SafeNET&7] Invalid format! Please use &6/sn generate [length, greater than 0] &7to generate a new passphrase of the specified length, or &6/sn reload &7to reload the plugin."
  # If a new passphrase is being generated (/sn generate <length>):
  generate: "&7[&6SafeNET&7] New passphrase has been generated and set into the configuration file. Please, use &6/sn reload &7to apply the new passphrase now."
  # If plugin configuration is being reloaded (/sn reload):
  reload: "&7[&6SafeNET&7] The plugin has been reloaded!"