#┌-----┐                                            ┌--┐ ┌--┐  ┌--┐           ┌--┐                             ┌--┐
#|   ┌-┘                                            |  | |   \ |  |           |  |                             |  |
#|   └-┐ ┌-----┐ ┌-----┐ ┌-┐ ┌-┐ ┌-----┐ ┌-----┐ ┌--┘  | |    \|  | ┌-----┐ ┌-┘  └-┐ ┌-┐┌-┐┌-┐ ┌-----┐ ┌-----┐ |  | ┌--┐
#└--┐  | |  -  | |  ┌--┘ | | | | |  ┌--┘ |  -  | | ┌-┐ | |  \  \  | |  -  | └-┐  ┌-┘ | || || | | ┌-┐ | |  ┌--┘ |  └┘  /
#   |  | | ┌---┘ |  |    | | | | |  |    | ┌---┘ | | | | |  |\    | | ┌---┘   |  |   | || || | | | | | |  |    |  ┌┐  \
#┌--┘  | | └---┐ |  └--┐ | └-┘ | |  |    | └---┐ | └-┘ | |  | \   | | └---┐   |  |   | └┘ └┘ | | └-┘ | |  |    |  |\   \
#└-----┘ └-----┘ └-----┘ └-----┘ └--┘    └-----┘ └-----┘ └--┘  └--┘ └-----┘   └--┘   └-------┘ └-----┘ └--┘    └--┘ └--┘
# Plugin made by dejvokep.
#
# ► Need any help?
# Join the Discord server (https://discord.com/invite/BbhADEy) and we will more than happily help you :) (nonstop 24/7 bot support)
#
# Config version:
# - Note: Do not change unless you know what you are doing. Changing this might break the plugin.
config-version: 1
# Passphrase:
# - Info: It is recommended to change this once in a while. Generate a new one using "/sn generate".
passphrase: ""
# Disconnect message sent to the player if their connection is unauthorized:
# - Info: "\n" can be used for a new line.
disconnect-message: "&7[&6SecuredNetwork&7] &cPlease connect with IP: yourserver.com!\n\n&7&oIf you believe this is an error, contact server administrators."
# Enable metrics - anonymous data sending including but not limited to country in which is the server hosted, number of
# cores, amount of players online. These statistics are used to determine the usage of the plugin and are freely
# viewable online.
# - Note: When changed, to take effect server restart is needed.
metrics: true
# IP whitelisting:
# - Note: This is NOT any kind of security feature, just a "decoration".
ip-whitelist:
  # Enable:
  enabled: false
  # Whitelisted IPs - these should be the proxy IPs / DNS names (these are just examples, please, delete them if you
  # want to use this feature):
  # - Info: Port must be specified after each IP separated by colon (IP:port). If the connecting player used any of
  #         these IPs, their connection will be allowed.
  #         If your server has dynamic IP, use the "{ip}" placeholder as the server's IP. Please configure the
  #         ip-website field, too.
  #         Please note that your DNS server also accepts YoUrSERVER.com (or similarly formatted) requests. By default,
  #         exactly the specified IPs / DNS names are compared. If you want to allow also these, case-randomly formatted
  #         DNS addresses, including hostnames..., please surround that whitelisted IP by brackets []. Example:
  #         [test.yourserver.com] will allow also TeSt.YOuRserVER.cOm. In case of any questions, visit the wiki, please.
  #         For better readability, you can put spaces (" ") anywhere you want. These will be removed after the plugin
  #         processes the whitelisted IPs. Example: "a . b . c . yourserver . com".
  # - Note: The only accepted IPs are IPv4 formatted addresses.
  ips: [ ]
  # Website used to obtain the value of the "{ip}" placeholder (the IP of your server):
  # - Info: This should be a website that returns only your IP on the GET request (if you open it on your browser).
  # - Note: The Author of the plugin is not responsible for any privacy information and/or data leaks. Pick a server
  #         carefully.
  ip-website: ""
# Update checker:
updater:
  # Enable:
  # - Info: Recommended having this enabled, so you are always informed about new updates carrying for example
  #         important security patches. THE UPDATER WILL NOT NOTIFY YOU IF NO UPDATE IS AVAILABLE.
  enabled: true
  # Delay between re-checking for update in minutes (set to -1 to check only once):
  delay: 60
  # Message to send if there is a new update available:
  # - Placeholders: {version_latest} - the latest plugin version
  #                 {version_current} - currently used plugin version
  message: "&7[&6SecuredNetwork&7] New update of &6SecuredNetwork plugin &7has been released (&6{latest_version}&7). You are using &6{current_version}&7. Please update as soon as possible."
# Command messages:
command:
  # If player runs the command:
  console-only: "&7[&6SecuredNetwork&7] Command is available only in the console."
  # If sender uses an invalid format of a command:
  invalid-format: "&7[&6SecuredNetwork&7] Invalid format! Please use &6/sn generate [length, greater than 0] &7to generate a new passphrase of the specified length, or &6/sn reload &7to reload the plugin."
  # If a new passphrase is being generated (/sn generate <length>):
  generate: "&7[&6SecuredNetwork&7] New passphrase has been generated and set into the configuration file. Please, use &6/sn reload &7to apply the new passphrase now."
  # If plugin configuration is being reloaded (/sn reload):
  reload: "&7[&6SecuredNetwork&7] The plugin has been reloaded!"