#┌-----┐                                            ┌--┐ ┌--┐  ┌--┐           ┌--┐                             ┌--┐
#|   ┌-┘                                            |  | |   \ |  |           |  |                             |  |
#|   └-┐ ┌-----┐ ┌-----┐ ┌-┐ ┌-┐ ┌-----┐ ┌-----┐ ┌--┘  | |    \|  | ┌-----┐ ┌-┘  └-┐ ┌-┐┌-┐┌-┐ ┌-----┐ ┌-----┐ |  | ┌--┐
#└--┐  | |  -  | |  ┌--┘ | | | | |  ┌--┘ |  -  | | ┌-┐ | |  \  \  | |  -  | └-┐  ┌-┘ | || || | | ┌-┐ | |  ┌--┘ |  └┘  /
#   |  | | ┌---┘ |  |    | | | | |  |    | ┌---┘ | | | | |  |\    | | ┌---┘   |  |   | || || | | | | | |  |    |  ┌┐  \
#┌--┘  | | └---┐ |  └--┐ | └-┘ | |  |    | └---┐ | └-┘ | |  | \   | | └---┐   |  |   | └┘ └┘ | | └-┘ | |  |    |  |\   \
#└-----┘ └-----┘ └-----┘ └-----┘ └--┘    └-----┘ └-----┘ └--┘  └--┘ └-----┘   └--┘   └-------┘ └-----┘ └--┘    └--┘ └--┘
#Plugin made by davidcubesvk.
#
# ► Don't understand / know how to set up?
# All terms and setup process are available on my website. Link is in all of my plugins' descriptions.
# ► Need any help?
# Contact me through any of listed methods on my website, I'd like to help!
#
# Property used to forward the passphrase to a backend server:
property:
  # Name of the property (can not be "textures"):
  # - Info: This can be used also as the second passphrase - another layer of security.
  #         If used that way, it is recommended to change this once in a while.
  name: "secured_network"
  # Value of the property - the actual passphrase (the longer it is, the better, but do not choose too long passphrase,
  # otherwise, it will take long for slower connections to join):
  # - Info: It is recommended to change this once in a while.
  value: ""
# Disconnect message sent to the player if:
# - Info: "\n" can be used for a new line.
disconnect:
  # A not whitelisted IP was used to join the server:
  whitelist:
    # The default message used when no filtering IP applies:
    default: "&7[&6SecuredNetwork&7] &cPlease connect with IP: yourserver.com!"
    # Message filtering by IP:
    # - Info: If you do not wish to use this feature, just leave it as "filters: []"
    filters: []
    #    # The IP player used to connect (specified the same way as in IP whitelist):
    #  - ip: ""
    #    # The message to use when the filter applies:
    #    message: ""
  # An error occurred while setting the passphrase into the connection:
  passphrase-error: "&7[&6SecuredNetwork&7] &cAn error occurred while processing your request.\n\n&7&oPlease try again later."
# Enable the plugin's own logging system:
# - Info: Plugin's log files are saved into "logs" folder in it's plugin folder. It is recommended to have it disabled if
#         you are not encountering any problems and/or errors.
log: false
# Enable metrics - anonymous data sending including but not limited to country in which is the server hosted, number of
# cores, amount of players online. These statistics are used to determine the usage of the plugin.
# - Note: When changed, to take effect server restart is needed.
metrics: true
# IP whitelisting:
ip-whitelist:
  # Enable:
  enabled: false
  # Whitelisted IPs - these should be the proxy IPs / DNS names (these are just examples, please, delete them if you want to use this feature):
  # - Info: Wildcard character can be used as a replacement for string of any length (except the dot ".") and specified
  #         by "*". For example, "*.yourserver.com" will allow players connecting with any hostname - it is not
  #         specified exactly. Please make sure you've placed the wildcard on the desired positions. You can also use
  #         wildcard as an IP part (an IP part is part of the IP surrounded by dots from both side or port colon ":"
  #         from one side...), "123.*.*.321" will allow players connecting through "123.010.255.321"... For more
  #         information about these mechanics, please visit the plugin wiki available at davidcubesvk.com.
  #         To block all hostname for a IP, simply insert only the IP without any hostname - e.g. "yourserver.com" will
  #         allow only players connecting with "yourserver.com".
  #         If your server has dynamic IP, use the "{ip}" placeholder as the server's IP.
  #         To allow case-insensitive hostname comparing for the current IP, insert "[CASE_INSENSITIVE]" prefix right
  #         before the IP as shown in an example IP below. The "[CASE_SENSITIVE]" prefix indicates case-sensitive
  #         comparing. If there's no prefix, the IP is compared case-sensitively.
  #         Writing a port is required.
  # - Note: The only accepted IPs are IPv4 addresses.
  ips:
    - "{ip}:25577"
    - "yourserver.com:25577"
    - "localhost:25577"
    - "[CASE_INSENSITIVE] abc.yourserver.com:25577"
  # Website used to obtain the value of the "{ip}" placeholder (the IP of your server):
  # - Info: This should be a website that returns only your IP on the GET request (if you open it on your browser).
  ip-website: "https://checkip.amazonaws.com/"
# Update checker:
updater:
  # Enable:
  # - Info: Recommended to have this enabled so you are always informed about new updates with for example important
  #         security patches.
  enabled: true
  # Delay between re-checking for update in minutes (set to -1 to check only once):
  delay: 60
  # Messages:
  # - Info: To disable a message, leave it as "".
  # - Placeholders: {version_latest} - the latest plugin version
  #                 {version_current} - currently used plugin version
  messages:
    # If there is a new update available:
    update: "&7[&6SecuredNetwork&7] New update of &6SecuredNetwork plugin &7has been released (&6{latest_version}&7). You are using &6{current_version}&7. Please update as soon as possible."
    # If using the latest version:
    latest: ""
# Command messages:
command:
  # If player runs the command:
  console-only: "&7[&6SecuredNetwork&7] Command is available only in the console."
  # If sender uses an invalid format of a command:
  invalid-format: "&7[&6SecuredNetwork&7] Invalid format! Please use &6/sn generate <length, greater than 0> &7to generate a new passphrase of the specified length, or &6/sn reload &7to reload the plugin."
  # If a new passphrase is being generated (/sn generate <length>):
  generate: "&7[&6SecuredNetwork&7] New passphrase has been generated and set into the configuration file. Please, use &6/sn reload &7to apply the new passphrase now."
  # If plugin configuration is being reloaded (/sn reload):
  reload: "&7[&6SecuredNetwork&7] The plugin has been reloaded!"