#┌-----┐                                            ┌--┐ ┌--┐  ┌--┐           ┌--┐                             ┌--┐
#|   ┌-┘                                            |  | |   \ |  |           |  |                             |  |
#|   └-┐ ┌-----┐ ┌-----┐ ┌-┐ ┌-┐ ┌-----┐ ┌-----┐ ┌--┘  | |    \|  | ┌-----┐ ┌-┘  └-┐ ┌-┐┌-┐┌-┐ ┌-----┐ ┌-----┐ |  | ┌--┐
#└--┐  | |  -  | |  ┌--┘ | | | | |  ┌--┘ |  -  | | ┌-┐ | |  \  \  | |  -  | └-┐  ┌-┘ | || || | | ┌-┐ | |  ┌--┘ |  └┘  /
#   |  | | ┌---┘ |  |    | | | | |  |    | ┌---┘ | | | | |  |\    | | ┌---┘   |  |   | || || | | | | | |  |    |  ┌┐  \
#┌--┘  | | └---┐ |  └--┐ | └-┘ | |  |    | └---┐ | └-┘ | |  | \   | | └---┐   |  |   | └┘ └┘ | | └-┘ | |  |    |  |\   \
#└-----┘ └-----┘ └-----┘ └-----┘ └--┘    └-----┘ └-----┘ └--┘  └--┘ └-----┘   └--┘   └-------┘ └-----┘ └--┘    └--┘ └--┘
# Plugin made by davidcubesvk. Credit for some parts of this plugin including but not limited to the core (passphrase)
# functioning goes to project BungeeGuard (https://github.com/lucko/BungeeGuard) and it's contributors.
#
# ► Don't understand / know how to set up?
# All terms and setup process are available on my website. Link is in all of my plugins' descriptions.
# ► Need any help?
# Contact me through any of listed methods on my website, I'd like to help!
#
# Property used to forward the passphrase from the proxy server (fill with the same data as on the proxy servers):
property:
  # Name of the property (can not be "textures" - reserved for the game protocol):
  # - Info: This can be used also as the second passphrase - another layer of security.
  name: "secured_network"
  # Value of the property - the actual passphrase:
  # - Info: It is recommended to change this once in a while.
  #         The longer it is, the better, but do not choose too long passphrase, otherwise, it will take long for slower
  #         connections to join, recommended length: 1000)
  value: ""
# Block server pings for unauthenticated requests:
block-pings: false
# Disconnect message sent to the player if bypassing the proxy (failed the authentication - invalid passphrase, property):
# - Info: "\n" can be used for a new line.
disconnect-failed-authentication: "&7[&6SecuredNetwork&7] &cPlease connect with IP: yourserver.com!"
# Enable the plugin's own logging system:
# - Info: Plugin's log files are saved into "logs" folder in it's plugin folder. It is recommended to have it disabled if
#         you are not encountering any problems and/or errors.
log: false
# Command messages:
command:
  # If a player runs the command:
  console-only: "&7[&6SecuredNetwork&7] Command is available only in the console."
  # If the sender uses an invalid format of a command:
  invalid-format: "&7[&6SecuredNetwork&7] Invalid format! Please use &6/sn reload &7to reload the plugin, or &6/sn connection-logger <attach|detach> [uuid|all] to manage the connection logger."
  # If plugin configuration is being reloaded (/sn reload):
  reload: "&7[&6SecuredNetwork&7] The plugin (except the logger) has been reloaded!"
  # Connection logger
  connection-logger:
    # If the connection logger attached:
    # - Placeholders: {uuid} - the UUID to which the logger attached
    attached: "&7[&6SecuredNetwork&7] Connection logger attached to &6{uuid}&7. The logger will detach automatically detach after the specified player joins, or do that manually via &6/sn connection-logger detach&7."
    # If the connection logger attached:
    detached: "&7[&6SecuredNetwork&7] Connection logger detached."