#┌-----┐                                            ┌--┐ ┌--┐  ┌--┐           ┌--┐                             ┌--┐
#|   ┌-┘                                            |  | |   \ |  |           |  |                             |  |
#|   └-┐ ┌-----┐ ┌-----┐ ┌-┐ ┌-┐ ┌-----┐ ┌-----┐ ┌--┘  | |    \|  | ┌-----┐ ┌-┘  └-┐ ┌-┐┌-┐┌-┐ ┌-----┐ ┌-----┐ |  | ┌--┐
#└--┐  | |  -  | |  ┌--┘ | | | | |  ┌--┘ |  -  | | ┌-┐ | |  \  \  | |  -  | └-┐  ┌-┘ | || || | | ┌-┐ | |  ┌--┘ |  └┘  /
#   |  | | ┌---┘ |  |    | | | | |  |    | ┌---┘ | | | | |  |\    | | ┌---┘   |  |   | || || | | | | | |  |    |  ┌┐  \
#┌--┘  | | └---┐ |  └--┐ | └-┘ | |  |    | └---┐ | └-┘ | |  | \   | | └---┐   |  |   | └┘ └┘ | | └-┘ | |  |    |  |\   \
#└-----┘ └-----┘ └-----┘ └-----┘ └--┘    └-----┘ └-----┘ └--┘  └--┘ └-----┘   └--┘   └-------┘ └-----┘ └--┘    └--┘ └--┘
# Plugin made by davidcubesvk. Credit for some parts of this plugin including but not limited to the core (passphrase)
# functioning goes to project BungeeGuard (https://github.com/lucko/BungeeGuard) and it's contributors.
#
# ► Don't understand / know how to set up?
# All terms and setup process are available on my website. Link is in all of my plugins' descriptions.
# ► Need any help?
# Contact me through any of listed methods on my website, I'd like to help!
#
# Property used to forward the passphrase to a backend server:
property:
  # Name of the property (can not be "textures"):
  # - Info: This can be used also as the second passphrase - another layer of security.
  #         If used that way, it is recommended to change this once in a while.
  name: "secured_network"
  # Value of the property - the actual passphrase (the longer it is, the better, but do not choose too long passphrase,
  # otherwise, it will take long for slower connections to join, recommended length: 100):
  # - Info: It is recommended to change this once in a while.
  value: ""
# Disconnect message sent to the player if:
# - Info: "\n" can be used for a new line.
disconnect:
  # A not whitelisted IP was used to join the server:
  whitelist: "&7[&6SecuredNetwork&7] &cPlease connect with IP: yourserver.com!"
  # An error occurred while setting the passphrase into the connection:
  passphrase-error: "&7[&6SecuredNetwork&7] &cAn error occurred while processing your request.\n\n&7&oPlease try again later. If the problem persists, contact server administrators."
# Enable the plugin's own logging system:
# - Info: Plugin's log files are saved into "logs" folder in it's plugin folder. It is recommended to have it disabled
#         if you are not encountering any problems and/or errors.
log: false
# Enable metrics - anonymous data sending including but not limited to country in which is the server hosted, number of
# cores, amount of players online. These statistics are used to determine the usage of the plugin.
# - Note: When changed, to take effect server restart is needed.
metrics: true
# IP whitelisting:
# - Note: This is NOT any kind of security feature, just a "decoration".
ip-whitelist:
  # Enable:
  enabled: false
  # Whitelisted IPs - these should be the proxy IPs / DNS names (these are just examples, please, delete them if you
  # want to use this feature):
  # - Info: Port should be specified after each IP separated by colon (IP:port). If the connecting player used any of
  #         these IPs, their connection will be allowed.
  #         If your server has dynamic IP, use the "{ip}" placeholder as the server's IP. Please configure the
  #         ip-website field, too.
  #         Please note that your DNS server also accepts YoUrSERVER.com (or similarly formatted) requests. By default,
  #         exactly the specified IPs / DNS names are compared. If you want to allow also these, case-randomly formatted
  #         DNS addresses, including hostnames..., please surround that whitelisted IP by brackets []. Example:
  #         [test.yourserver.com] will allow also TeSt.YOuRserVER.cOm. In case of any questions, visit the wiki, please.
  #         For better readability, you can put spaces (" ") anywhere you want. These will be removed after the plugin
  #         processes the whitelisted IPs. Example: "a . b . c . your server . com".
  # - Note: The only accepted IPs are IPv4 formatted addresses.
  ips: [ ]
  # Website used to obtain the value of the "{ip}" placeholder (the IP of your server):
  # - Info: This should be a website that returns only your IP on the GET request (if you open it on your browser).
  # - Note: The Author of the plugin is not responsible for any privacy information and/or data leaks. Pick a server
  #         carefully.
  ip-website: ""
# Update checker:
updater:
  # Enable:
  # - Info: Recommended to have this enabled, so you are always informed about new updates carrying for example
  #         important security patches.
  enabled: true
  # Delay between re-checking for update in minutes (set to -1 to check only once):
  delay: 60
  # Messages:
  # - Info: To disable a message, leave it as "".
  # - Placeholders: {version_latest} - the latest plugin version
  #                 {version_current} - currently used plugin version
  messages:
    # If there is a new update available:
    update: "&7[&6SecuredNetwork&7] New update of &6SecuredNetwork plugin &7has been released (&6{latest_version}&7). You are using &6{current_version}&7. Please update as soon as possible."
    # If using the latest version:
    latest: ""
# Command messages:
command:
  # If player runs the command:
  console-only: "&7[&6SecuredNetwork&7] Command is available only in the console."
  # If sender uses an invalid format of a command:
  invalid-format: "&7[&6SecuredNetwork&7] Invalid format! Please use &6/sn generate <length, greater than 0> &7to generate a new passphrase of the specified length, or &6/sn reload &7to reload the plugin."
  # If a new passphrase is being generated (/sn generate <length>):
  generate: "&7[&6SecuredNetwork&7] New passphrase has been generated and set into the configuration file. Please, use &6/sn reload &7to apply the new passphrase now."
  # If plugin configuration is being reloaded (/sn reload):
  reload: "&7[&6SecuredNetwork&7] The plugin has been reloaded!"