#┌-----┐                                            ┌--┐ ┌--┐  ┌--┐           ┌--┐                             ┌--┐
#|   ┌-┘                                            |  | |   \ |  |           |  |                             |  |
#|   └-┐ ┌-----┐ ┌-----┐ ┌-┐ ┌-┐ ┌-----┐ ┌-----┐ ┌--┘  | |    \|  | ┌-----┐ ┌-┘  └-┐ ┌-┐┌-┐┌-┐ ┌-----┐ ┌-----┐ |  | ┌--┐
#└--┐  | |  -  | |  ┌--┘ | | | | |  ┌--┘ |  -  | | ┌-┐ | |  \  \  | |  -  | └-┐  ┌-┘ | || || | | ┌-┐ | |  ┌--┘ |  └┘  /
#   |  | | ┌---┘ |  |    | | | | |  |    | ┌---┘ | | | | |  |\    | | ┌---┘   |  |   | || || | | | | | |  |    |  ┌┐  \
#┌--┘  | | └---┐ |  └--┐ | └-┘ | |  |    | └---┐ | └-┘ | |  | \   | | └---┐   |  |   | └┘ └┘ | | └-┘ | |  |    |  |\   \
#└-----┘ └-----┘ └-----┘ └-----┘ └--┘    └-----┘ └-----┘ └--┘  └--┘ └-----┘   └--┘   └-------┘ └-----┘ └--┘    └--┘ └--┘
#Plugin made by davidcubesvk.
#
# ► Don't understand / know how to set up?
# All terms and setup process are available on my website. Link is in all of my plugins' descriptions.
# ► Need any help?
# Contact me through any of listed methods on my website, I'd like to help!
#
# Property used to forward the passphrase from the proxy server (fill with the same data as on the proxy servers):
property:
  # Name of the property (can not be "textures"):
  # - Info: This can be used also as the second passphrase - another layer of security.
  #         If used that way, it is recommended to change this once in a while.
  name: "secured_network"
  # Value of the property - the actual passphrase (the longer it is, the better, but do not choose too long passphrase, otherwise, it will take long for slower connections to join):
  # - Info: It is recommended to change this once in a while.
  value: ""
# Block server pings:
block-pings: false
# Disconnect message sent to the player if bypassing the proxy (failed the authentication - invalid passphrase, property):
# - Info: "\n" can be used for a new line.
disconnect-failed-authentication: "&7[&6SecuredNetwork&7] &cPlease connect with IP: yourserver.com!"
# Enable the plugin's own logging system:
# - Info: Plugin's log files are saved into "logs" folder in it's plugin folder. It is recommended to have it disabled if
#         you are not encountering any problems and/or errors.
log: false
# Command messages:
command:
  # If player runs the command:
  console-only: "&7[&6SecuredNetwork&7] Command is available only in the console."
  # If sender uses an invalid format of a command:
  invalid-format: "&7[&6SecuredNetwork&7] Invalid format! Please use &6/sn reload &7to reload the plugin."
  # If plugin configuration is being reloaded (/sn reload):
  reload: "&7[&6SecuredNetwork&7] The plugin (except the logger) has been reloaded!"