# Plugin info:
name: ${parent.name}
version: ${parent.version}
author: davidcubesvk
main: com.davidcubesvk.securedNetworkBackend.SecuredNetworkBackend
description: ${parent.description}
api-version: 1.13
# Dependencies:
depend:
  - ProtocolLib
# Commands:
commands:
  securednetwork:
    description: "The main command of plugin SecuredNetwork, reloads the plugin."
    usage: /securednetwork reload
  sn:
    description: "The main command of plugin SecuredNetwork, reloads the plugin."
    usage: /sn reload