# Plugin info:
name: ${parent.name}
version: ${parent.version}
author: dejvokep
main: dev.dejvokep.securednetwork.spigot.SecuredNetworkSpigot
description: ${parent.description}
api-version: 1.13
# Dependencies:
depend:
  - ProtocolLib
# Commands:
commands:
  securednetwork:
    description: "The main command of SecuredNetwork plugin."
    usage: /securednetwork
  sn:
    description: "The main command of SecuredNetwork plugin."
    usage: /sn